### PR TITLE
Enhance Swagger Specification Management and Client Generation

### PR DESCRIPTION
**Pull request by KnockOutEZ**
This PR introduces improvements to the Swagger specification management and client generation process:

1. Moved all api client related files/packges to the client directory.

2. Updated Makefile with new targets

3. Seperated swagger spec for better clarity and maintainability

These changes streamline our API client development workflow, improve code organization. The modular approach to API specs will allow easier management of large APIs and promote code reuse.

Note: Ensure you have Python 3 and the pyyaml package installed (`pip install pyyaml`).

### CODE REVIEW

**Review by jason-lynch — APPROVED** [review]
I think this looks good! Something that might be worth looking into: I ended up with different results when I ran `make generate-client` myself. Maybe I got a newer version of the swagger CLI from `make install` since you have it set to install `@latest`?

**Comment by KnockOutEZ** [comment]
> I think this looks good! Something that might be worth looking into: I ended up with different results when I ran `make generate-client` myself. Maybe I got a newer version of the swagger CLI from `make install` since you have it set to install `@latest`?

Thanks for the review Jason. I updated the swagger CLI and its still generating the same results. Can you please check if [go-swagger](https://github.com/go-swagger/go-swagger) is running the generate command or any other swagger cli. 

You can also push the changes here and we can revert later after checking.

**Comment by jason-lynch** [comment]
@KnockOutEZ I opened a PR into your branch so that you can take a look at the diff: #5

**Comment by jason-lynch** [comment]
At least part of the diff originates from this change: https://github.com/go-swagger/go-swagger/commit/4ea55ab5a088f7c22f43f3edadc325ff208a8775

Which was only released in the latest version v0.31.0. You can check which version you have by running `swagger version`.

**Pull request merged**
